# Generated by Django 5.0.6 on 2024-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("logo", models.CharField(max_length=256)),
                ("slug_name", models.SlugField(max_length=64, unique=True)),
                ("is_multi_tenant", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [models.Index(fields=["slug_name"], name="slug_name_idx")],
            },
        ),
    ]
