# Generated by Django 5.0.6 on 2025-03-07 08:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("logo", models.CharField(max_length=256)),
                ("slug_name", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "total_devices",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_by", models.UUIDField()),
            ],
            options={
                "indexes": [models.Index(fields=["slug_name"], name="slug_name_idx")],
            },
        ),
    ]
