# Generated by Django 5.0.6 on 2024-07-12 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="is_multi_tenant",
        ),
        migrations.AddField(
            model_name="space",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_space",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
