# Generated by Django 5.0.6 on 2025-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
