# Generated by Django 5.0.6 on 2024-11-06 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0002_remove_space_is_multi_tenant_space_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="total_devices",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
