# Generated by Django 5.0.6 on 2025-10-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0002_space_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
