# Generated by Django 5.0.6 on 2026-04-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0003_space_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="build_artifact",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
