# Generated by Django 5.0.6 on 2026-04-16 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0004_space_build_artifact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="build_artifact",
        ),
    ]
