# Generated by Django 5.0.6 on 2026-04-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0005_remove_space_build_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="build_artifact",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
