# Generated by Django 5.0.6 on 2026-05-07 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0006_space_build_artifact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="build_artifact",
        ),
    ]
