# Generated by Django 5.0.6 on 2026-05-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("smart_building", "Smart Building"),
                    ("smart_fleet_monitor", "Smart Fleet Monitor"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
