# Generated by Django 5.0.6 on 2024-06-21 07:20

from common.apps.organization_role.constants import OrganizationPermission
from django.db import migrations

default_policies = [
    {
        "name": "Administrator access",
        "description": "Provides full access to services and resources",
        "tags": ["administrator"],
        "permissions": [permission.value for permission in OrganizationPermission],
    },
    {
        "name": "Organization full access",
        "description": "Grants full access to Organization resources and access to related services",
        "tags": ["organization", "full access"],
        "permissions": [
            OrganizationPermission.UPDATE_ORGANIZATION,
            OrganizationPermission.DELETE_ORGANIZATION,
        ],
    },
    {
        "name": "Organization's Role read-only access",
        "description": "Provide read only access to Organization's Role services",
        "tags": ["organization-role", "read-only"],
        "permissions": [
            OrganizationPermission.READ_ORGANIZATION_ROLE,
        ],
    },
    {
        "name": "Organization's Role full access",
        "description": "Grants full access to Organization's Role resources and access to related services",
        "tags": ["organization-role", "full-access"],
        "permissions": [
            OrganizationPermission.READ_ORGANIZATION_ROLE,
            OrganizationPermission.CREATE_ORGANIZATION_ROLE,
            OrganizationPermission.UPDATE_ORGANIZATION_ROLE,
            OrganizationPermission.DELETE_ORGANIZATION_ROLE,
        ],
    },
    {
        "name": "Organization's Member read-only access",
        "description": "Provide read only access to Organization's Member services",
        "tags": ["organization-member", "read-only"],
        "permissions": [
            OrganizationPermission.READ_ORGANIZATION_MEMBER,
        ],
    },
    {
        "name": "Organization's Member full access",
        "description": "Grants full access to Organization's Member resources and access to related services",
        "tags": ["organization-member", "full-access"],
        "permissions": [
            OrganizationPermission.READ_ORGANIZATION_MEMBER,
            OrganizationPermission.INVITE_ORGANIZATION_MEMBER,
            OrganizationPermission.UPDATE_ORGANIZATION_MEMBER_ROLE,
            OrganizationPermission.REMOVE_ORGANIZATION_MEMBER,
        ],
    },
]


def create_default_policy(apps, schema_editor):
    OrganizationPolicy = apps.get_model("organization_role", "OrganizationPolicy")

    for policy in default_policies:
        OrganizationPolicy(**policy).save()


class Migration(migrations.Migration):
    dependencies = [
        ("organization_role", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_policy)]
