# Generated by Django 5.0.6 on 2024-06-26 10:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("space", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpacePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), size=None
                    ),
                ),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("UPDATE_SPACE", "Update Space"),
                                ("DELETE_SPACE", "Delete Space"),
                                ("READ_SPACE_ROLE", "Read Space Role"),
                                ("CREATE_SPACE_ROLE", "Create Space Role"),
                                ("UPDATE_SPACE_ROLE", "Update Space Role"),
                                ("DELETE_SPACE_ROLE", "Delete Space Role"),
                                ("READ_SPACE_MEMBER", "Read Space Member"),
                                ("INVITE_SPACE_MEMBER", "Invite Space Member"),
                                (
                                    "UPDATE_SPACE_MEMBER_ROLE",
                                    "Update Space Member Role",
                                ),
                                ("REMOVE_SPACE_MEMBER", "Remove Space Member"),
                                ("READ_DASHBOARD", "Read Dashboard"),
                                ("CREATE_DASHBOARD", "Create Dashboard"),
                                ("UPDATE_DASHBOARD", "Update Dashboard"),
                                ("DELETE_DASHBOARD", "Delete Dashboard"),
                                ("READ_DEVICE_STATE", "Read Device State"),
                            ],
                            max_length=256,
                        ),
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpaceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("policies", models.ManyToManyField(to="space_role.spacepolicy")),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_role",
                        to="space.space",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpaceRoleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_role_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_role_user",
                        to="space_role.spacerole",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
