# Generated by Django 5.0.6 on 2025-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space_role", "0002_create_default_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="spaceroleuser",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
