# Generated by Django 5.0.6 on 2025-03-18 04:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationuser",
            name="avatar",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="location",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="title",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="providers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("google", "Google"),
                        ("", "None Provider"),
                        ("space_df", "Space Df"),
                    ],
                    max_length=256,
                    null=True,
                ),
                default=[""],
                size=None,
            ),
        ),
    ]
