# Generated by Django 4.2.15 on 2024-08-19 03:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationuser",
            name="providers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("google", "Google"), ("None", "None Provider")],
                    max_length=256,
                    null=True,
                ),
                default=["None"],
                size=None,
            ),
        ),
    ]
