# Generated by Django 5.0.6 on 2024-11-06 04:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization_user", "0002_organizationuser_providers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="providers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("google", "Google"),
                        ("None", "None Provider"),
                        ("space_df", "Space DF"),
                    ],
                    max_length=256,
                    null=True,
                ),
                default=["None"],
                size=None,
            ),
        ),
    ]
