from django.db import models


class OrganizationPermission(models.TextChoices):
    # Organization
    UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION"
    DELETE_ORGANIZATION = "DELETE_ORGANIZATION"

    # Organization Role
    READ_ORGANIZATION_ROLE = "READ_ORGANIZATION_ROLE"
    CREATE_ORGANIZATION_ROLE = "CREATE_ORGANIZATION_ROLE"
    UPDATE_ORGANIZATION_ROLE = "UPDATE_ORGANIZATION_ROLE"
    DELETE_ORGANIZATION_ROLE = "DELETE_ORGANIZATION_ROLE"

    # Organization Member
    READ_ORGANIZATION_MEMBER = "READ_ORGANIZATION_MEMBER"
    INVITE_ORGANIZATION_MEMBER = "INVITE_ORGANIZATION_MEMBER"
    UPDATE_ORGANIZATION_MEMBER_ROLE = "UPDATE_ORGANIZATION_MEMBER_ROLE"
    REMOVE_ORGANIZATION_MEMBER = "REMOVE_ORGANIZATION_MEMBER"
