from django.db import models


class OrganizationRoleType(models.TextChoices):
    OWNER_ROLE = "Owner"
    ADMIN_ROLE = "Admin"
    EDITOR_ROLE = "Editor"
    VIEWER_ROLE = "Viewer"


class OrganizationPermission(models.TextChoices):
    # Organization
    UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION"
    DELETE_ORGANIZATION = "DELETE_ORGANIZATION"

    # Organization Role
    READ_ORGANIZATION_ROLE = "READ_ORGANIZATION_ROLE"
    CREATE_ORGANIZATION_ROLE = "CREATE_ORGANIZATION_ROLE"
    UPDATE_ORGANIZATION_ROLE = "UPDATE_ORGANIZATION_ROLE"
    DELETE_ORGANIZATION_ROLE = "DELETE_ORGANIZATION_ROLE"

    # Organization Member
    READ_ORGANIZATION_MEMBER = "READ_ORGANIZATION_MEMBER"
    INVITE_ORGANIZATION_MEMBER = "INVITE_ORGANIZATION_MEMBER"
    UPDATE_ORGANIZATION_MEMBER_ROLE = "UPDATE_ORGANIZATION_MEMBER_ROLE"
    REMOVE_ORGANIZATION_MEMBER = "REMOVE_ORGANIZATION_MEMBER"

    # Organization Device
    READ_ORGANIZATION_DEVICE = "READ_ORGANIZATION_DEVICE"
    CREATE_ORGANIZATION_DEVICE = "CREATE_ORGANIZATION_DEVICE"
    UPDATE_ORGANIZATION_DEVICE = "UPDATE_ORGANIZATION_DEVICE"
    DELETE_ORGANIZATION_DEVICE = "DELETE_ORGANIZATION_DEVICE"
