from django.db import models


class SpacePermission(models.TextChoices):
    # Space
    UPDATE_SPACE = "UPDATE_SPACE"
    DELETE_SPACE = "DELETE_SPACE"

    # Space Role
    READ_SPACE_ROLE = "READ_SPACE_ROLE"
    CREATE_SPACE_ROLE = "CREATE_SPACE_ROLE"
    UPDATE_SPACE_ROLE = "UPDATE_SPACE_ROLE"
    DELETE_SPACE_ROLE = "DELETE_SPACE_ROLE"

    # Space Member
    READ_SPACE_MEMBER = "READ_SPACE_MEMBER"
    INVITE_SPACE_MEMBER = "INVITE_SPACE_MEMBER"
    UPDATE_SPACE_MEMBER_ROLE = "UPDATE_SPACE_MEMBER_ROLE"
    REMOVE_SPACE_MEMBER = "REMOVE_SPACE_MEMBER"

    # Dashboard
    READ_DASHBOARD = "READ_DASHBOARD"
    CREATE_DASHBOARD = "CREATE_DASHBOARD"
    UPDATE_DASHBOARD = "UPDATE_DASHBOARD"
    DELETE_DASHBOARD = "DELETE_DASHBOARD"

    # Device state
    READ_DEVICE_STATE = "READ_DEVICE_STATE"
